export enum PERMISSION {
  CAN_CREATE_REAL_ESTATE = 'CAN_CREATE_REAL_ESTATE',
  CAN_READ_REAL_ESTATE = 'CAN_READ_REAL_ESTATE',
  CAN_UPDATE_REAL_ESTATE = 'CAN_UPDATE_REAL_ESTATE',
  CAN_DELETE_REAL_ESTATE = 'CAN_DELETE_REAL_ESTATE',
  //
  CAN_CREATE_ADDRESS = 'CAN_CREATE_ADDRESS',
  CAN_READ_ADDRESS = 'CAN_READ_ADDRESS',
  CAN_UPDATE_ADDRESS = 'CAN_UPDATE_ADDRESS',
  CAN_DELETE_ADDRESS = 'CAN_DELETE_ADDRESS',
  //
  CAN_READ_PERSON = 'CAN_READ_PERSON',
  CAN_UPDATE_PERSON = 'CAN_UPDATE_PERSON',
  //
  CAN_ASSIGN_USER_IN_ROLE = 'CAN_ASSIGN_USER_IN_ROLE',
  CAN_UNLINK_USER_IN_ROLE = 'CAN_UNLINK_USER_IN_ROLE',
  //
  CAN_READ_ROLE = 'CAN_READ_ROLE',
  //
  CAN_CREATE_MENU = 'CAN_CREATE_MENU',
  CAN_UPDATE_MENU = 'CAN_UPDATE_MENU',
  CAN_DELETE_MENU = 'CAN_DELETE_MENU',
  //
  CAN_CREATE_CUSTOMER = 'CAN_CREATE_CUSTOMER',
  CAN_READ_CUSTOMER = 'CAN_READ_CUSTOMER',
  CAN_UPDATE_CUSTOMER = 'CAN_UPDATE_CUSTOMER',
  CAN_DELETE_CUSTOMER = 'CAN_DELETE_CUSTOMER',
  //
  CAN_CREATE_TYPE = 'CAN_CREATE_TYPE',
  CAN_READ_TYPE = 'CAN_READ_TYPE',
  CAN_UPDATE_TYPE = 'CAN_UPDATE_TYPE',
  CAN_DELETE_TYPE = 'CAN_DELETE_TYPE',
  //
  CAN_CREATE_PROPERTY = 'CAN_CREATE_PROPERTY',
  CAN_READ_PROPERTY = 'CAN_READ_PROPERTY',
  CAN_UPDATE_PROPERTY = 'CAN_UPDATE_PROPERTY',
  CAN_DELETE_PROPERTY = 'CAN_DELETE_PROPERTY',
}
